### ISSUE TITLE
Observability: StackDriver Integration

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#541]
**Problem**
High-level issue for Observability related tasks. 
TL'DR we should be able to integrate with SD metrics, tracing, and logging.

There has been worked done already in this space. We are mainly lacking Source metrics, as it requires integration with SD backend so that users are not charged. But we need to verify traces and logging are actually working as expected. And maybe move away from span-based tracing if it will simplify things. E2E tests need to be added. Our new Broker impl should also support our current metrics (present in the channel-based one, in the Broker ingress and filter pods), as well as tracing

- [ ] Metrics
    - [x] Broker/Trigger metrics for new Broker impl https://github.com/google/knative-gcp/issues/649
    - [ ] E2E tests
       - [x] Tests for Trigger metrics https://github.com/google/knative-gcp/issues/647
       - [x] Tests for Broker metrics https://github.com/google/knative-gcp/issues/648
       - [x] Fix e2e test problem in Prow https://github.com/google/knative-gcp/issues/317
       - [ ] Test for channel https://github.com/google/knative-gcp/issues/287

 - [ ] Tracing
    - [x] Tracing through new Broker impl https://github.com/google/knative-gcp/issues/650
    - [ ] Tracing through channel https://github.com/google/knative-gcp/issues/226
    - [x] E2E tests
       - [x] Re-enable tests https://github.com/google/knative-gcp/issues/652
       - [x] Tests more lenient https://github.com/knative/eventing/issues/2046 (release/1)
       - [x] Trace context propagation https://github.com/knative/eventing/issues/2559 (release/2?)

- [ ] Logging
    - [ ] E2E test https://github.com/google/knative-gcp/issues/651

 **[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Exit Criteria**
Integration with SD metrics in sources, tracing, and logging.

**Time Estimate (optional):** 
???

**Comment by nachocano** [comment]
fyi @liu-cong @nlopezgi

**Comment by nachocano** [comment]
/assign @ian-mi as I know you have started working on some tracing stuff. 
This can be considered an umbrella issue, where you can start putting your findings on... Together with the openCensus patching one in eventing

**Comment by nachocano** [comment]
We should scope this down to multiple issues

**Comment by nachocano** [comment]
We should make sure that the new Broker implementation support our current SD metrics

**Comment by nachocano** [comment]
re: the metris list in eventing https://github.com/knative/eventing/issues?q=is%3Aopen+metrics+author%3Anachocano+label%3Aarea%2Fobservability+. IMO we can safely skip it for now, as they were mainly targeting prometheus backends, and we need to explicitly test our SD integration.

**Comment by Harwayne** [comment]
/close

Closing as all the release/1, priority/1 issues are closed. All remaining work items still have their own issues that can be prioritized independently.
